image: node:latest

before_script:
    - cd sample-app
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl

stages:
    - deployment

deployment:
    type: deploy
    tags:
      - dalfcs_gitlab_docker_ci
    stage: deployment
    image: ruby:latest
    script:
        - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
    only:
        - main
